[NEW ZOO-FUNCTIONS] Requisito 4 - isManager
betrybe/sd-0x-project-zoo-functions pull request #22
Opened 2021-07-29 14:21 UTC by alexandremhm

alterações:

- Reformula o Readme do projeto para o novo requisito isManager;
- Refatora os testes para se adequar ao novo requisito;
- Eleva a dificuldade do requisito isManager de fácil para moderado.

closes: #4898

2021-07-30 13:02 UTC, alexandremhm commented on README.md
> +    - [ORDEM DOS REQUISITOS NO AVALIADOR AUTOMÁTICO](#ordem-dos-requisitos-no-avaliador-automático)
Oi @cleytonoliveira vc quer dizer em relação a que especificamente?

2021-07-30 19:17 UTC, cleytonoliveira commented on README.md
> +    - [ORDEM DOS REQUISITOS NO AVALIADOR AUTOMÁTICO](#ordem-dos-requisitos-no-avaliador-automático)
Aos títulos. Acredito que seja pra evitar caixa alta. Acredito que fez isso por que esta em caixa alta ao decorrer do Readme, mas seria ideal corrigir eles. Vou deixar como sugestão.

2021-07-30 19:47 UTC, cleytonoliveira commented on README.md
> +    - [O QUE DEVERÁ SER DESENVOLVIDO](#o-que-deverá-ser-desenvolvido)
```suggestion
    - [O que deverá ser desenvolvido](#o-que-deverá-ser-desenvolvido)
```

2021-07-30 19:47 UTC, cleytonoliveira commented on README.md
> +    - [4. IMPLEMENTE AS FUNÇÕES isManager E employeeManagement](#4-implemente-as-funções-ismanager-e-employeemanagement)
```suggestion
    - [4. Implemente as funções `isManager` e `employeeManagement`](#4-implemente-as-funções-ismanager-e-employeemanagement)
```

2021-07-30 19:47 UTC, cleytonoliveira commented on README.md
> +### 4. IMPLEMENTE AS FUNÇÕES isManager E employeeManagement
```suggestion
### 4. Implemente as funções `isManager` e `employeeManagement`
```

2021-07-30 19:47 UTC, cleytonoliveira commented on README.md
> +Pensando em tudo isso, dividimos para você a função employeeManagement em duas funções. A primeira, isManager, é responsável por verificar se um `id` passado por parâmetro é de uma pessoa colaborador
```suggestion
Pensando em tudo isso, dividimos para você a função `employeeManagement` em duas funções. A primeira, `isManager`, deverá ser responsável por verificar se um `id` passado por parâmetro é de uma pessoa colaboradora gerente ou não. A segunda função, `employeeManagement` deverá utilizar a informação da primeira função considerando as seguintes condições:
```

2021-07-30 19:47 UTC, cleytonoliveira commented on README.md
> +Em sua vida de pessoa desenvolvedora, saber quebrar problemas maiores em menores ajudará a resolver problemas mais complexos de maneira mais fácil. Além disso, funções são blocos de códigos lógicos c
Acha que faz sentido esse paragrafo só para este requisito? Acredito que terá mais requisitos que vão utilizar deste padrão, não faria sentido colocar na parte de desenvolvimento ou algo assim?

2021-07-30 19:47 UTC, cleytonoliveira commented on README.md
> +    Exemplo de output: // [ 'Burl Bethea', 'Ola Orloff', 'Emery Elser' ];
```suggestion
- Retorna um array contendo nome e sobrenome das pessoas colaboradoras gerenciadas por determinada pessoa com cargo de gerência.
    Exemplo de output:
```javascript
[ 'Burl Bethea', 'Ola Orloff', 'Emery Elser' ];
```
```

2021-07-30 19:47 UTC, cleytonoliveira commented on README.md
> +    Exemplo de output: // [ '0e7b460e-acf4-4e17-bcb3-ee472265db83', 'fdb2543b-5662-46a7-badc-93d960fdc0a8' ];
```suggestion
    Exemplo de output:
```javascript
[ '0e7b460e-acf4-4e17-bcb3-ee472265db83', 'fdb2543b-5662-46a7-badc-93d960fdc0a8' ];
```
```

2021-07-30 19:47 UTC, cleytonoliveira commented on README.md
> +  - Se o id passado **não** for de um gerente, retorna um array contendo os id's dos gerentes responsáveis por ela;
```suggestion
  - Se o id passado **não** for de um gerente, retorna um array contendo os id's das pessoas gerentes responsáveis por ela;
```

2021-07-30 19:47 UTC, cleytonoliveira commented on test/isManager.test.js
> +describe('4 - Crie uma função que faça a gestão dos funcionários de acordo com o respectivo gerente', () => {
```suggestion
describe('4 - Crie uma função que faça a gestão das pessoas funcionárias de acordo com a respectiva pessoa gerente', () => {
```

2021-07-30 19:47 UTC, cleytonoliveira commented on test/isManager.test.js
> +    it('retorna o nome dos funcionarios do respectivo gerente', () => {
```suggestion
    it('retorna o nome das pessoas funcionárias do respectivo gerente', () => {
```

2021-07-30 19:47 UTC, cleytonoliveira commented on test/isManager.test.js
> +    it('caso não seja gerente, retorna o id do responsável pelo funcionário', () => {
```suggestion
    it('caso não seja gerente, retorna o id da pessoa responsável pela pessoa funcionária', () => {
```

2021-07-30 21:05 UTC, sheilatavares commented on README.md
> +Em sua vida de pessoa desenvolvedora, saber quebrar problemas maiores em menores ajudará a resolver problemas mais complexos de maneira mais fácil. Além disso, funções são blocos de códigos lógicos c
Ficou bem legal ter essa orientação para o pessoal! Porém concordo com o Cleyton, como teremos outros requisitos com essa prática creio que o ideal seria colocar em uma seção de dicas e não dentro do requisito. Seria algo como:

Dicas:
-  Quebrar suas funções em pequenos blocos de lógica tem inúmeras vantagens: reduz a complexidade, facilita a detecção de erros e a manutenção do código, além de que você poderá reutilizar esse bloco de código em outras partes de sua aplicação. Você verá nesse projeto que algumas funções se utilizam de outras funções de forma a se complementarem, facilitando a resolução. Utilize essa prática quando considerar útil para resolver problemas mais complexos!

2021-07-30 21:07 UTC, sheilatavares commented on README.md
> +Pensando em tudo isso, dividimos para você a função employeeManagement em duas funções. A primeira, isManager, é responsável por verificar se um `id` passado por parâmetro é de uma pessoa colaborador
Aqui, relacionando com o parágrafo sobre a prática de dividir em blocos de código menores, uma sugestão seria:

Considerando a boa prática de dividir o código em partes menores, apresentamos a função employeeManagement em que você deverá dividí-la em duas funções: a primeira - isManager - que será responsável por verificar uma pessoa colaboradora é gerente ou não, e a segunda - employeeManagement - que utiliza a primeira função para apresentar as seguintes saídas:

2021-08-02 17:37 UTC, cleytonoliveira approved these changes

2021-08-04 13:20 UTC, renanvamo commented on README.md
> +  Considerando a boa prática de dividir o código em partes menores, apresentamos a função employeeManagement em que você deverá dividí-la em duas funções: a primeira - isManager - que será responsáve
Ale, eu achei um pouco confusa a descrição do exercício.
Pra ficar mais claro poderia ser algo como 
```suggestion
Considerando a boa prática de dividir o código em partes menores, neste requisito você deve dividir o seu código em duas funções: 
1. isManager - que será responsável por verificar se uma pessoa colaboradora é gerente ou não 
2. employeeManagement - que utiliza a primeira função para apresentar as seguintes saídas:
```

2021-08-04 13:20 UTC, renanvamo commented on test/isManager.test.js
> +  describe('Implemente a função isManager', () => {
Ale, posso estar enganado, mas pelo que entendi o texto do 'it' deve ser o mesmo da seção 'o que será avaliado' no readme, se for realmente isso, talvez valeria a pena aplicar esse texto do it no lugar de 'o que será avaliado', mas seria legal confirmar isso.

2021-08-04 13:20 UTC, renanvamo commented on test/isManager.test.js
> +    it('retorna o nome das pessoas funcionárias do respectivo gerente', () => {
Como no primeiro 'it' você utilizou a primeira letra maiúscula, não faria sentido usar aqui e no pŕoximo it também?
```suggestion
    it('Retorna o nome das pessoas funcionárias do respectivo gerente', () => {
```

2021-08-04 13:20 UTC, renanvamo commented on test/isManager.test.js
> +    it('caso não seja gerente, retorna o id da pessoa responsável pela pessoa funcionária', () => {
```suggestion
    it('Caso não seja gerente, retorna o id da pessoa responsável pela pessoa funcionária', () => {
```

2021-08-04 20:54 UTC, gfpoliva commented on README.md
> +### 1. Implemente a função getSpeciesByIds
O que acha?

```suggestion
### 1. Implemente a função `getSpeciesByIds`
```

E se fizer sentido, aplicar nos outros locais

2021-08-04 20:54 UTC, gfpoliva commented on src/isManager.js
> +  // escreva sua função aqui
A função já está escrita. O que falta é a implementação. O que acha de

```suggestion
  // implemente a função
```

Se fizer sentido, refatorar nos outros locais tmb.

2021-08-05 00:14 UTC, NandaInstrucao commented on README.md
> +Em sua vida de pessoa desenvolvedora, saber quebrar problemas maiores em menores ajudará a resolver problemas mais complexos de maneira mais fácil. Além disso, funções são blocos de códigos lógicos c
Uma sugestão para esse trecho: 

`Em sua vida de pessoa desenvolvedora, o pensamento algoritmico, processo de quebrar problemas complexos em pequenas partes para resolvê-los, ajudará a solucionar de maneira mais fácil os problemas complexos. Assim, uma boa forma de começar a desenvolver um projeto é lembrar que as funções são compostas por pequenos blocos de lógica que têm finalidade (função) específica. Ou seja, quebrar as funções em pequenos blocos de lógica tornará tudo mais simples de se entender e você sempre poderá reutilizar esses códigos em outras partes de sua aplicação. `

Acho que ciatr a questão do pensamento algoritmico pode ajudar a apsaar a ideia de a pessoa dividir os problemas em pequenas partes para resolver.

2021-08-10 12:35 UTC, cleytonoliveira requested changes

2021-08-10 12:35 UTC, cleytonoliveira commented on README.md
>  ### 4. Implemente a função `isManager`
```suggestion
### 4. Implemente a função `getRelatedEmployees`
```
O que você acha? Acredito que devemos considerar a função que tem a saída final. Faz sentido?

2021-08-10 12:35 UTC, cleytonoliveira commented on test/getRelatedEmployees.test.js
> +describe('4 - Crie uma função que faça a gestão dos funcionários de acordo com o respectivo gerente', () => {
```suggestion
describe('4 - Crie a gestão dos funcionários de acordo com o respectivo gerente', () => {
```
Fiz essa alteração pois na realidade são duas funções, veja o que faz sentido.

2021-08-10 12:35 UTC, cleytonoliveira commented on README.md
> +  2 - `getRelatedEmployees` - que utiliza a primeira função para apresentar as seguintes saídas:
Quais saídas? O próximo tópico é observações técnicas, acho que da pra deixar mais nítido, o que acha?

2021-08-10 12:35 UTC, cleytonoliveira commented on README.md
Senti falta de informação sobre como lançar o erro, até porque este requisito esta antes do que o Paulo fez. Veja o que da pra adaptar do que o Paulo fez.

2021-08-10 12:38 UTC, alexandremhm commented on README.md
> +  2 - `getRelatedEmployees` - que utiliza a primeira função para apresentar as seguintes saídas:
Nossa passou batido essa parte mesmo hahaha

2021-08-10 12:45 UTC, alexandremhm commented on README.md
> +  2 - `getRelatedEmployees` - que utiliza a primeira função para apresentar as seguintes saídas:
```suggestion
Considerando a boa prática de dividir o código em partes menores, apresentamos a função `getRelatedEmployees` em que você deverá dividí-la em duas funções: 
  
  1 - `isManager` - que será responsável por verificar se uma pessoa colaboradora é gerente ou não. O retorno dessa função deve ser um booleano: `true`ou `false`;
  2 - `getRelatedEmployees` - que utiliza a primeira função para apresentar as seguintes saídas: 
     * se a pessoa colaboradora tiver cargo de gerente, deve retornar um array contendo os nomes das pessoas colaboradoras que ela é responsável;
     * se a pessoa colaboradora não tiver cargo de gerente, deve disparar um erro.
  
  
```

2021-08-10 14:56 UTC, isaacbatst commented on test/getRelatedEmployees.test.js
> +      expect(actual).toEqual(expected);(actual, expected);
```suggestion
      expect(actual).toEqual(expected);
```
Acho que sobrou esse trecho sem querer

2021-08-10 14:56 UTC, isaacbatst commented on README.md
> +throw new Error('Informações inválidas');
Será que uma dessas opções é válida?

- Ou uma sugestão de pesquisa: "Lançar objeto de erro javascript"
- Ou o link da [documentação](https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Error)

2021-08-11 12:04 UTC, cleytonoliveira approved these changes

2021-08-12 11:55 UTC, Luiz-Wendel approved these changes

2021-08-12 13:02 UTC, merged