[NEW ZOO] [calculateEntry]
betrybe/sd-0x-project-zoo-functions pull request #23
Opened 2021-07-29 15:15 UTC by paulohbsimoes

2021-07-30 13:32 UTC, alexandremhm approved these changes
Muito bom Paulo =)

2021-07-30 19:07 UTC, cleytonoliveira requested changes

2021-07-30 19:07 UTC, cleytonoliveira commented on test/calculateEntry.test.js
> +    });
Acho que essa parte que você falou em dividir em mais it, correto? Acho que também faça sentido.

2021-07-30 19:08 UTC, cleytonoliveira commented
Ficou bom demais Paulo. Achei que a progressão ficou bem legal.

2021-08-02 14:49 UTC, renanvamo commented on README.md
> +  - [6. Implemente a função calculateEntry](#6-implemente-a-função-calculateentry)
Fala Paulo, nessa linha aqui tem algum motivo a mudança do markdown? Eu fiquei um pouco confuso pelo motivo, ou foi apenas por engano?

2021-08-02 14:49 UTC, renanvamo commented on README.md
> +Você deve isolar parte da lógica na função `countEntrants` que se encontra no mesmo arquivo da função `calculateEntry`. Ela deverá receber o array de visitantes e retornar um objeto com a contagem de
```suggestion
Você deve isolar a parte da lógica na função `countEntrants` que se encontra no mesmo arquivo da função `calculateEntry`. Ela deverá receber o array de visitantes e retornar um objeto com a contagem de acordo com os seguintes critérios de classificação:
```

2021-08-02 17:30 UTC, cleytonoliveira approved these changes

2021-08-03 02:17 UTC, paulohbsimoes commented on README.md
> +  - [6. Implemente a função calculateEntry](#6-implemente-a-função-calculateentry)
Opa, é que se deixar em maiúsculo o link não funciona

2021-08-03 10:20 UTC, merged