Refazendo o requisito "getSchedule"
betrybe/sd-0x-project-zoo-functions pull request #28
Opened 2021-08-02 12:56 UTC by denis-rossati

**ALTERAÇÕES ~~e motivações~~**

Eu concordo muito com a proposta do novo requisito, por que fazer objetos dinâmicos nessa parte do curso foi especialmente difícil pra mim porque eu não entendia bem quais vantagens eu poderia tirar da notação de colchetes na hora de definir uma chave ou recuperar um dado de um objeto. Então refiz o requisito de modo que deve ficar meio difícil de fugir para uma solução que não use a criação de objetos com notação de colchetes.

Eu adicionei uma chave nova para cada animal, nela tem um array de dias em que o animal está disponível para se ver.

Mudei também os testes e o enunciado do README.

Agora o requisito é a pessoa implementar a função de modo que caso ela passe nenhum parâmetro ou algo que não seja um animal ou dia, a função vai retornar o horário de abertura e fechamento de todos os dias e o array de animais que estão disponíveis naquele dia. Caso passe apenas um animal, deverá retornar os dias em que ele está disponível. Caso passe um dia, vai retornar os horários do dia e quais animais estão disponíveis.

[link da issue](https://github.com/betrybe/course/issues/4911)

2021-08-02 18:07 UTC, cleytonoliveira commented on test/getSchedule.test.js
>      assert.deepStrictEqual(actual, expected);
Esses testes da pra passar com `it` mais específicos, o que acha?

2021-08-03 11:15 UTC, denis-rossati commented on test/getSchedule.test.js
>  describe('Implemente a função getSchedule', () => {
Faz sentido, vou adequar aqui.

2021-08-03 13:24 UTC, cleytonoliveira approved these changes

2021-08-03 14:46 UTC, renanvamo approved these changes

2021-08-03 14:46 UTC, renanvamo commented on README.md
> +  - Sem parâmetros, retorna um cronograma legível para humanos, com os horários para cada dia e quais animais estarão disponíveis.
Fala Denis, sei que não foi uma alteração sua, mas já que estamos mexendo no requisito, acho que ficaria mais natural trocar "humanos" por "pessoas" ou "visitantes", mas é apenas uma sugestão

2021-08-03 21:21 UTC, cleytonoliveira requested changes

2021-08-03 21:21 UTC, cleytonoliveira commented on test/getSchedule.test.js
> +  });
Acredito que pode ter um it só pra ele. Colocar no readme também essa hipótese.

2021-08-04 11:20 UTC, denis-rossati commented on README.md
> +  - Sem parâmetros, retorna um cronograma legível para humanos, com os horários para cada dia e quais animais estarão disponíveis.
de boas, também achei estranho na hora que li mas não sabia pelo que eu substituiria.

2021-08-04 11:20 UTC, denis-rossati commented on test/getSchedule.test.js
> +  });
Ahhh beleza, vou mudar isso.

2021-08-05 11:39 UTC, merged