[PROJECT REVIEW] Bloco 8-6-Reformar o requisito countAnimals
betrybe/sd-0x-project-zoo-functions pull request #29
Opened 2021-08-02 14:10 UTC by renanvamo

Alterações:
Refatora o exercício countAnimals, os testes e o Readme referente a esse requisito
---
closes: #4899
---
Automação:

2021-08-02 18:47 UTC, cleytonoliveira requested changes
Você fez rubrica para verificar seus testes? Gostaria de ver se esta próximo a minha solução.

2021-08-02 18:47 UTC, cleytonoliveira commented on test/countAnimals.test.js
> +    let actual = zoo.countAnimals({ specie: 'penguins' });
Acredito que tenha que alinhar com o arquivo `countAnimals.js`;

2021-08-02 18:47 UTC, cleytonoliveira commented on test/countAnimals.test.js
> +    actual = zoo.countAnimals({ specie: 'giraffes' });
ajustar aqui após alinhar

2021-08-02 19:11 UTC, cleytonoliveira commented on test/countAnimals.test.js
> +  it('Recebendo como parâmentro um objeto com a chave \'specie\', retorna um número com o total de animais daquela espécie', () => {
Abra outro describe acima do já existente com o número do requisito. Ex:
```javascript
describe('5 - Crie uma função que realiza a contagem dos animais', () => {
 // demais testes
}
```

2021-08-03 13:31 UTC, cleytonoliveira commented on src/countAnimals.js
> +function countAnimals() {
```suggestion
function countAnimals(species) {
```
Acho que da pra manter o parâmetro

2021-08-03 15:00 UTC, sheilatavares commented on README.md
> +  - Recebendo como parâmentro um objeto com a chave `specie`, retorna um número com o total de animais daquela espécie
```suggestion
  - Recebendo como parâmetro um objeto com a chave `specie`, retorna um número com o total de animais daquela espécie
```

2021-08-03 15:00 UTC, sheilatavares commented on test/countAnimals.test.js
> +    it('Recebendo como parâmentro um objeto com a chave \'specie\', retorna um número com o total de animais daquela espécie', () => {
```suggestion
    it('Recebendo como parâmetro um objeto com a chave \'specie\', retorna um número com o total de animais daquela espécie', () => {
```

2021-08-04 12:31 UTC, renanvamo commented on src/countAnimals.js
> +function countAnimals() {
Boa, vou fazer isso, mas acho que como ele vai receber um objeto que pode receber specie e genre como chave, talvez um nome diferente seja melhor.

2021-08-04 21:09 UTC, fndcaique reviewed
Acredito que seja melhor utilizarmos a palavra `animal` para quando estivermos falando sobre um animal específico (com id) ou `animais` quando forem todos os animais de uma espécie, para simplificar o entendimento e utilizarmos a palavra `espécie` quando nos referirmos a `leões`, `girafas`, etc

2021-08-05 00:24 UTC, NandaInstrucao commented on README.md
>    Esta função é responsável por contabilizar a quantidade de animais.
Gostei da sugestão do @fndcaique

2021-08-05 00:24 UTC, NandaInstrucao commented on README.md
> +  - Com o argumento `specie: 'penguins'`, retorna um número com a quantidade de pinguins no zoológico
Sugiro as seguintes alterações: 
- Se nenhum argumento for passado, retorna um objeto cujo nome da espécie é uma chave e a quantidade total de animais dessa espécie é o valor; 
- Com o argumento `specie: 'penguins'`, a quantidade de pinguins no zoológico. 
:)

2021-08-05 12:34 UTC, renanvamo commented on README.md
> +  - Com o argumento `specie: 'penguins'`, retorna um número com a quantidade de pinguins no zoológico
Gostei das sugestões, embora o segundo ponto da Nanda eu acho que pode ficar confuso, a intenção é justamente explicitar que o retorno é um número, e não um objeto, diferente do primeiro argumento.

2021-08-05 14:24 UTC, renanvamo commented on README.md
> +  - Com o argumento `specie: 'giraffes', genre: 'female'`, retorna um número com a quantidade de girafas do gênero feminino
Faz bastante sentido

2021-08-06 18:52 UTC, cleytonoliveira commented on test/countAnimals.test.js
> +
```suggestion
```

2021-08-06 18:53 UTC, cleytonoliveira approved these changes

2021-08-09 11:28 UTC, denis-rossati approved these changes
Muito bom, só deixei uma sugestão mas fica a seu critério se é melhor mudar ou não

2021-08-09 11:28 UTC, denis-rossati commented on README.md
> +  - Recebendo como parâmetro um objeto com a chave `specie` e `genre`, retorna um número, a quantidade de animais daquela espécie, no gênero selecionado
```suggestion
  - Recebendo como parâmetro um objeto com a chave `specie` e `genre`, retorna um número que é a quantidade de animais daquela espécie, no gênero selecionado
```

É só uma sugestão qualquer, mas acho que assim ficou melhor de se ler. Oq achas?

2021-08-09 11:28 UTC, denis-rossati commented on test/countAnimals.test.js
> +    it('Recebendo como parâmetro um objeto com a chave \'specie\' e \'genre\', retorna um número, a quantidade de animais daquela espécie, no gênero selecionado', () => {
Caso queira mudar o enunciado ali em cima, vou deixar a sugestão aqui pra vc não precisa dar outro push pra mudar o nome do teste 

```suggestion
    it(Recebendo como parâmetro um objeto com a chave \`specie`\ e \`genre`\, retorna um número que é a quantidade de animais daquela espécie, no gênero selecionado, () => {
```

2021-08-10 11:10 UTC, renanvamo commented on README.md
> +  - Recebendo como parâmetro um objeto com a chave `specie` e `genre`, retorna um número, a quantidade de animais daquela espécie, no gênero selecionado
Fala Dennis, acho que fica bom sim, mas como eu já alterei essa mesma frase por sugestão de alguém da instrução, acho que faz sentido deixar dessa forma

2021-08-10 11:14 UTC, merged