[CONTENT REVIEW] 8.5 - Atualização Readme projeto Zoo
betrybe/sd-0x-project-zoo-functions pull request #8
Opened 2020-11-13 17:59 UTC by lauroandrade

- Atualização do Readme do projeto para o novo padrão. 

Referências:
[_Issue_](https://github.com/betrybe/course/issues/2239)
[Sprint 27](https://docs.google.com/presentation/d/1cfsBfzl2EJTVo2G8X8G1rhKTGgpW3Dou1_dMQlSWlG0/edit?ts=5f9c0d3f#slide=id.ga560a05ea3_0_3)

2020-11-16 11:40 UTC, LizzardMedeiros requested changes

2020-11-16 11:40 UTC, LizzardMedeiros commented on README.md
> +- [Requisitos do projeto](#requisitos-do-projeto)
Nos requisitos, é bom colocar exatamente como estão escritos e o número deles!

2020-11-16 11:40 UTC, LizzardMedeiros commented on README.md
> +### 1. IMPLEMENTE A FUNÇÃO animalsByIds
Além do comando do requisito, é bom fazer uma descrição mais detalhada do que o estudante deverá fazer. Os _its_ você pode colocar logo depois, com a descrição: _O que será avaliado:_

2020-11-16 16:38 UTC, lauroandrade commented on README.md
> +  - [employeeCoverage](#13-implemente-a-função-employeeCoverage)
```suggestion
  - [1. Implemente a função animalsByIds](#1-implemente-a-função-animalsByIds)
  - [2. Implemente a função animalsOlderThan](#2-implemente-a-função-animalsOlderThan)
  - [3. Implemente a função employeeByName](#3-implemente-a-função-employeeByName)
  - [4. Implemente a função createEmployee](#4-implemente-a-função-createEmployee)
  - [5. Implemente a função isManager](#5-implemente-a-função-isManager)
  - [6. Implemente a função addEmployee](#6-implemente-a-função-addEmployee)
  - [7. Implemente a função animalCount](#7-implemente-a-função-animalCount)
  - [8. Implemente a função entryCalculator](#8-implemente-a-função-entryCalculator)
  - [9. Implemente a função animalMap](#9-implemente-a-função-animalMap)
  - [10. Implemente a função schedule](#10-implemente-a-função-schedule)
  - [11. Implemente a função oldestFromFirstSpecies](#11-implemente-a-função-oldestFromFirstSpecies)
  - [12. Implemente a função increasePrices](#12-implemente-a-função-increasePrices)
  - [13. Implemente a função employeeCoverage](#13-implemente-a-função-employeeCoverage)
```

2020-11-17 12:03 UTC, LizzardMedeiros approved these changes
Ficou muito bom!

2020-12-03 16:30 UTC, LucasCFerraz commented on README.md
> +- Produzir código legível, conciso e expressivo utilizando as novas funcionalidades do ES6
@lauroandrade essa sugestão de o que verificamos foi retirada dos 'ser capaz de'?

2020-12-03 17:14 UTC, lauroandrade commented on README.md
> +- Produzir código legível, conciso e expressivo utilizando as novas funcionalidades do ES6
Não sei se todas elas...
Era pra retirar?

2020-12-03 17:48 UTC, LucasCFerraz commented on README.md
> +- Produzir código legível, conciso e expressivo utilizando as novas funcionalidades do ES6
@albertosca sua sugestão aqui :D

2020-12-03 21:21 UTC, LucasCFerraz approved these changes

2020-12-03 21:30 UTC, merged